#!/bin/bash

h=src/dm42/device.rs
q=rscalc_qspi.bin


filesize() {
	stat -Lc%s "$1"
}


if [ ! -f "$q" ];then
	echo "ERROR: Missing qspi file '$q'"
	exit 1
fi

if [ ! -f "$h" ]; then
	sz=0
	crc=0
else
	sz=`cat $h  | grep QSPI_DATA_SIZE | awk '{print $5}'`
	crc=`cat $h | grep QSPI_DATA_CRC  | awk '{print $5}'`
fi

nsz=`filesize $q`\;
ncrc=0x`crc32 $q`\;

if [ $sz != $nsz -o $crc != $ncrc ]; then
	cat << OI
====
QSPI Contents changed:
   Size:   $sz	-> $nsz
    CRC:   $crc	-> $ncrc
====
OI
	exit 1
fi
